core/urls.py
from django.conf.urls         import url
from django.views.generic     import TemplateView
from django.utils.translation import ugettext_lazy as _
from .                        import views

urlpatterns = [
    url(r'^$',           views.home,                                      name = 'home'),
    url(_(r'^hq$'),      TemplateView.as_view(template_name = 'hq.html'), name = 'hq'),
    url(_(r'^map$'),     views.map,                                       name = 'map'),
    url(_(r'^friends$'), views.friends,                                   name = 'friends'),
]

sugarcub/urls.py
from django.conf.urls         import include, url, i18n
from django.contrib           import admin
from django.conf              import settings
from django.conf.urls.static  import static
from django.utils.translation import ugettext_lazy as _
from django.contrib.auth      import views as auth_views
from users.forms              import AuthenticationForm


urls = [
    url(r'^captcha/', include('captcha.urls')),
    url(_(r'admin/doc/'), include('django.contrib.admindocs.urls')),
    url(_(r'admin/'),     include(admin.site.urls)),

    url(_(r'bbbff/'),     include('bbbff.urls',  namespace='bbbff')),
    url(_(r'agenda/'),    include('agenda.urls', namespace='agenda')),
    url(r'',              include('users.urls',  namespace='users')),
    url(r'',              include('core.urls',   namespace='core')),

    url(r'^login/$',
        auth_views.login,
        {
            'template_name': 'registration/login.html',
            'authentication_form': AuthenticationForm
        },
        name='auth_login'),
    url(r'',              include('registration.backends.default.urls')),
]


urlpatterns = i18n.i18n_patterns(*urls)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


handler400 = 'core.views.bad_request'
handler403 = 'core.views.permission_denied'
handler404 = 'core.views.page_not_found'
handler500 = 'core.views.server_error'

users/urls.py
from django.conf.urls         import url
from django.views.generic     import TemplateView
from django.utils.translation import ugettext_lazy as _
from .                        import views


urlpatterns = [
    url(_(r'^members$'),  views.members,                    name = 'members'),
    url(_(r'^profile$'),  views.profile,                    name = 'profile'),
    url(_(r'^register$'), views.RegistrationView.as_view(), name = 'registration_register'),
    url(_(r'^register/informations$'),
        TemplateView.as_view(template_name = 'registration/informations.html'),  name = 'pre_register'),
]

users/models.py
from   django.db                  import models
from   django.contrib.auth.models import User
from   stdimage.models            import StdImageField
from   stdimage.utils             import UploadToUUID
from   django.core.validators     import RegexValidator, MinLengthValidator
from   django.utils.translation   import ugettext_lazy as _
from   datetime                   import date, timedelta
from   contextlib                 import suppress
from   celery                     import shared_task
from   .                          import fields, validators
import requests


class UrlField(models.CharField):
    default_validators = [validators.UrlValidator()]

    def __init__(self, verbose_name=None, name=None, **kwargs):
        kwargs['max_length'] = kwargs.get('max_length', 200)
        super().__init__(**kwargs)

    def formfield(self, **kwargs):
        defaults = {
            'form_class': fields.UrlField,
        }
        defaults.update(kwargs)
        return super(UrlField, self).formfield(**defaults)


class ProfileManager(models.Manager):
    ''' Manager of the Profile model '''

    def get_active_users(self):
        '''
        Return a QuerySet of all profiles of active users
        ie profile.enabled == True and user.is_active == True
        '''

        return self.model.objects.filter(enabled = True, user__is_active = True)

    def get_birthday(self):
        ''' Return all profile with birthday today '''

        return self.model.objects.filter(birthday__day = date.today().day, birthday__month = date.today().month,
            enabled = True, user__is_active = True, birthday_enabled = True)

    def get_new_members(self):
        ''' Return profile registered within the last 30 days '''

        return self.model.objects.filter(
            user__date_joined__range=(date.today() - timedelta(days=30), date.today()),
            enabled = True, user__is_active = True)


class Profile(models.Model):
    ''' Represent extra data about a User '''

    objects           = ProfileManager()
    phone_regex       = RegexValidator(regex=r'^\+?1?\d{9,15}$', message=_(
        "Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed."))
    zipcode_regex     = RegexValidator(regex=r'^\d[1-9]\d{3}$', message=_(
        "The postal code must be 5 digits."))

    user              = models.OneToOneField(User, verbose_name = _('user'))

    enabled           = models.BooleanField(_('enabled'), default = False)
    name_enabled      = models.BooleanField(_('name enabled'), default = True)
    mail_enabled      = models.BooleanField(_('mail enabled'), default = True)

    bio_min_size      = MinLengthValidator(150, message=_(
        'The bio should be longer than 150 character'))
    bio               = models.TextField(_('bio'), validators=[bio_min_size])
    avatar            = StdImageField(_('avatar'), blank = True, null = True,
        variations = {'avatar': (100, 100), 'small': (50, 50), 'big': (222, 222)},
        upload_to  = UploadToUUID(path = 'avatars'),
    )

    phone             = models.CharField(_('phone'), validators=[phone_regex], max_length=15)
    phone_enabled     = models.BooleanField(_('phone enabled'), default = True)

    birthday          = models.DateField(_('birthday'))
    birthday_enabled  = models.BooleanField(_('birthday enabled'), default = True)

    address           = models.CharField(_('address'), max_length=200)
    city              = models.CharField(_('city'), max_length=30)
    postal_code       = models.CharField(_('postal code'), max_length=5, validators=[zipcode_regex])
    address_enabled   = models.BooleanField(_('address enabled'), default = True)

    address_longitude = models.FloatField(_('longitude'), blank = True, null = True)
    address_latitude  = models.FloatField(_('latitude'), blank = True, null = True)

    class Meta:
        verbose_name        = _('profile')
        verbose_name_plural = _('profiles')

    def __str__(self):
        return self.user.username

    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)
        get_gps_position.delay(self.id)


@shared_task
def get_gps_position(profile_id):
    ''' Update latitude and longitude form address using nominatim api '''

    profile = Profile.objects.get(pk = profile_id)

    with suppress(Exception):
        doc = requests.get(
            'https://nominatim.openstreetmap.org/search',
            {'q': profile.address + ' ' + profile.city, 'format': 'json'}
        ).json()

        profile.address_latitude = float(doc[0]['lat'])
        profile.address_longitude = float(doc[0]['lon'])


class Pony(models.Model):
    ''' List of different pony available '''

    name      = models.CharField(_('name'), max_length = 32)
    file_name = models.CharField(_('file name'), max_length = 32)

    class Meta:
        verbose_name        = _('pony icon')
        verbose_name_plural = _('pony icons')

    def __str__(self):
        return self.name


class Icon(models.Model):
    ''' List of different icon available '''

    name      = models.CharField(_('name'), max_length = 32)

    class Meta:
        verbose_name        = _('site icon')
        verbose_name_plural = _('site icons')

    def __str__(self):
        return self.name


class UserPony(models.Model):
    ''' List of ponies with little quotes to display in the user's description '''

    profile = models.ForeignKey(Profile, verbose_name = _('profile'))
    pony    = models.ForeignKey(Pony, verbose_name = _('pony'))
    message = models.CharField(_('message'), max_length = 64)

    class Meta:
        verbose_name        = _('pony')
        verbose_name_plural = _('ponies')

    def __str__(self):
        try:
            return self.message % self.pony
        except TypeError:
            return self.message


class UserUrl(models.Model):
    ''' List of urls in the user's description '''

    profile = models.ForeignKey(Profile, verbose_name = _('profil'))
    url     = UrlField(_('url'))
    icon    = models.ForeignKey(Icon, verbose_name = _('icon'))

    class Meta:
        verbose_name        = _('url')
        verbose_name_plural = _('urls')

    def __str__(self):
        return self.url

users/forms.py
from django                      import forms
from .                           import models
from django.contrib.auth.models  import User
from bootstrap3_datetime.widgets import DateTimePicker
from django.utils.translation    import ugettext_lazy as _
from multiform                   import MultiModelForm, InvalidArgument
from registration.forms          import RegistrationFormUniqueEmail
from django.contrib.auth.forms   import AuthenticationForm as _AuthenticationForm


class UserForm(forms.ModelForm):

    class Meta:
        model  = User
        fields = ['first_name', 'last_name']


class UserPonyForm(forms.ModelForm):

    class Meta:
        model = models.UserPony
        fields = ['pony', 'message']

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['message'].widget.attrs.update({'placeholder':
            _('Exemple : Pony is best pegasus/pony/unicorn!')
        })


class ProfileForm(forms.ModelForm):

    birthday = forms.DateTimeField(
        widget = DateTimePicker(
            options = {
                'format': 'DD/MM/YYYY',
                'viewMode': 'years',
            }
        ),
        label = _("Birthday")
    )

    class Meta:
        model   = models.Profile
        fields = [
            'bio', 'avatar', 'phone', 'birthday', 'address', 'city', 'postal_code',
            'name_enabled', 'phone_enabled', 'birthday_enabled', 'address_enabled', 'mail_enabled'
        ]
        labels = {
            'bio': _('Biography'),
            'phone': _('Phone'),
            'address': _('Address'),
            'city': _('City'),
            'postal_code': _('Postal code'),
            'name_enabled': _('Show my firstname and lastname (When hidden only your pseudo will be visible)'),
            'phone_enabled': _('Show my phone number (When hidden your will only be rechable by email'),
            'birthday_enabled': _('Show my birthday (When hidden nobody will know your age or your birthday)'),
            'address_enabled': _('Show my address (When hidde nyou will not appear on the members map'),
            'mail_enabled': _('Show my email'),
        }

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['bio'].widget.attrs.update({'placeholder':
            _('Write about yourself! how you discover My Little Pony or BronyCUB, '
                'what you like and dislike...')
        })


class RegistrationForm(MultiModelForm):

    base_forms = [
        ('registration', RegistrationFormUniqueEmail),
        ('user',         UserForm),
        ('profile',      ProfileForm),
    ]

    def dispatch_init_instance(self, name, instance):
        if name == 'registration':
            return InvalidArgument
        return super().dispatch_init_instance(name, instance)

    def save(self, commit=True, user=None):
        ''' Save both forms and attach the user to the profile. '''
        instances = self._combine('save', call=True, ignore_missing=True, call_kwargs={'commit': False})

        user.first_name = instances['user'].first_name
        user.last_name  = instances['user'].last_name
        instances['user'] = user

        instances['profile'].user = user
        instances['profile'].save()
        instances['user'].save()

        return instances


class AuthenticationForm(_AuthenticationForm):

    username = forms.CharField(max_length=256, label = _('Username or email'))

users/views.py
from   django.shortcuts                    import render
from   .                                   import models, forms, utils
from   django.contrib.auth.decorators      import login_required
from   django.forms.models                 import inlineformset_factory
from   registration.backends.default.views import RegistrationView as BaseRegistrationView
import random
import logging


class RegistrationView(BaseRegistrationView):

    form_class = forms.RegistrationForm

    def register(self, form):
        user = super().register(form['registration'])
        profile = form.save(user = user)['profile']
        utils.send_admin_registration_notification.delay(profile.id)
        return user


def members(request):

    users = list(models.Profile.objects.get_active_users())
    random.shuffle(users)

    return render(request, 'members.html', {
        'profiles': users,
    })


@login_required
def profile(request):

    # Get the user's profile
    try:
        profile = models.Profile.objects.get(user = request.user.id)
    except:
        profile = models.Profile()
        profile.user = request.user

    # inline formset for profile's pony
    ponyformset = inlineformset_factory(
        models.Profile, models.UserPony, form = forms.UserPonyForm, fields = ('pony', 'message',), extra = 0
    )

    # inline formset for profile's url
    urlformset = inlineformset_factory(models.Profile, models.UserUrl, fields = ('icon', 'url',), extra = 0)

    if request.method == 'POST':

        # To add a new row for pony (avoid using JS)
        if 'add_pony' in request.POST:
            cp = request.POST.copy()
            cp['pony-TOTAL_FORMS'] = int(cp['pony-TOTAL_FORMS']) + 1

            form = forms.ProfileForm(request.POST, request.FILES, instance = profile)
            ponies = ponyformset(cp, prefix = 'pony')
            urls = urlformset(request.POST, instance = profile, prefix='url')

        # To add a new row for url (avoid using JS)
        if 'add_url' in request.POST:
            cp = request.POST.copy()
            cp['url-TOTAL_FORMS'] = int(cp['url-TOTAL_FORMS']) + 1

            form = forms.ProfileForm(request.POST, request.FILES, instance = profile)
            ponies = ponyformset(request.POST, instance = profile, prefix = 'pony')
            urls = urlformset(cp, prefix='url')

        # When submitting information
        if 'submit' in request.POST:
            form = forms.ProfileForm(request.POST, request.FILES, instance = profile)
            ponies = ponyformset(request.POST, instance = profile, prefix = 'pony')
            urls = urlformset(request.POST, instance = profile, prefix = 'url')

            if form.is_valid():
                form.save()

                form = forms.ProfileForm(instance = profile)

            if ponies.is_valid():
                ponies.save()

                ponies = ponyformset(instance = profile, prefix = 'pony')

            if urls.is_valid():
                urls.save()

                urls = urlformset(instance = profile, prefix = 'url')

    else:
        form = forms.ProfileForm(instance = profile)
        ponies = ponyformset(instance = profile, prefix = 'pony')
        urls = urlformset(instance = profile, prefix = 'url')

    return render(request, 'profile.html', {
        'profile': profile,
        'form':    form,
        'ponies':  ponies,
        'urls':    urls,
    })

users/templates/members/one-user-link.html
{% load static %}

{% load i18n %}

<div class="col-sm-6 col-md-4">
    <a data-toggle="modal" data-target="#modal-{{profile.user.username}}" class="member-link">
        <div class="thumbnail panel-member">
            <span>
                <img class="img-rounded img-avatar" alt="avatar" src="
                    {% if profile.avatar %}
                        {{ profile.avatar.avatar.url }}
                    {% else %}
                        {% static 'ressources/logo/icon_bronycub.png' %}
                    {% endif %}">
            </span>
            <h3 class="username-member">{{ profile.user.username }}</h3>
        </div>
    </a>
</div>
{% include 'members/one-user-modal.html' with profile=profile %}

users/templates/members/one-user-modal.html
{% load static %}

{% load i18n %}

<div id="modal-{{profile.user.username}}" class="modal fade" role="dialog" aria-hidden="true">
	<div class="modal-dialog modal-lg">
		{% if user.is_authenticated and user.profile.enabled %}
		<div class="container-fluid modal-content modal-lg">
			<div class="modal-header">
				<button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
				<img class="img-rounded img-avatar" alt="avatar" src="
				{% if profile.avatar %}
				{{ profile.avatar.avatar.url }}
				{% else %}
				{% static 'ressources/logo/icon_bronycub.png' %}
				{% endif %}
				">
				<strong class="username">{{ profile.user.username }}</strong>
			</div>
			<div class="modal-body">
				<p class="pre-line">
				{{ profile.bio }}
				</p>
				<hr />
				<p>
				{% for pony in profile.userpony_set.all %}
				<img alt="{% static pony.pony.name %}" src="{% static 'img/ponies/'|add:pony.pony.file_name %}" class="img-thumbnail"/>&nbsp;<span class='label label-info'>{{ pony.message }}</span>
				{% endfor %}
				</p>
				{% if profile.userpony_set.all|length > 0 %}
				<hr />
				{% endif %}
				<div class="list-group col-sm-7">
					{% if profile.name_enabled %}
					<a href="#" class="list-group-item"><i class="fa fa-user">&nbsp;</i>{{ profile.user.last_name }} {{ profile.user.first_name }}</a>
					{% endif %}
					{% if profile.birthday_enabled %}
					<a href="#" class="list-group-item"><i class="fa fa-birthday-cake">&nbsp;</i>{{ profile.birthday }}</a>
					{% endif %}
					{% if profile.phone_enabled %}
					<a href="#" class="list-group-item"><i class="fa fa-phone">&nbsp;</i>{{ profile.phone }}</a>
					{% endif %}
					{% if profile.mail_enabled %}
					<a href="#" class="list-group-item"><i class="fa fa-envelope">&nbsp;</i>{{ profile.user.email }}</a>
					{% endif %}
					{% if profile.address_enabled %}
					<a href="#" class="list-group-item"><i class="fa fa-map-marker">&nbsp;</i>{{ profile.address }}, {{ profile.postal_code }} {{ profile.city }}</a>
					<a href="{% url 'core:map' %}" class="list-group-item"><i class="fa fa-map-marker">&nbsp;</i><button class="btn btn-info btn-xs">Localisation sur la carte</button></a>
					{% endif %}
				</div>
				<div class="panel-body">
					<div>
						{% for url in profile.userurl_set.all %}
						{% if url.icon.name|lower == 'email' %}
						<a href='mailto:{{ url.url }}' class='zocial icon {{ url.icon.name | lower }}'></a>
						{% else %}
						<a href='{{ url.url }}' class='zocial icon {{ url.icon.name | lower }}'></a>
						{% endif %}
						{% endfor %}
					</div>
				</div>
			</div>
		</div>
		{% elif user.is_authenticated and not user.profile.enabled %}
		<div class="container-fluid">
			<div class="alert alert-danger">
				<div class="row modal-body">
					<p>{% trans 'Your account must be accepted by the admin to see the members informations.' %}</p>
				</div>
				<div class="row modal-footer">
					<button type="button" class="btn btn-default" data-dismiss="modal">{% trans 'Close' %}</button>
				</div>
			</div>
		</div>
		{% else %}
		<div class="container-fluid">
			<div class="alert alert-danger">
				<div class="row modal-body">
					<p>{% trans 'You must be connected to see the members informations.' %}</p>
				</div>
				<div class="row modal-footer">
					<button type="button" class="btn btn-default" data-dismiss="modal">{% trans 'Close' %}</button>
				</div>
			</div>
		</div>
		{% endif %}
	</div>
</div>

users/templates/members/one-user.html
{% load static %}

{% load i18n %}

<div class="col-sm-6 col-md-4">
    <a data-toggle="modal" data-target="#modal-{{profile.user.username}}" class="member-link">
        <div class="thumbnail panel-member">
            <span>
                <img class="img-rounded img-avatar" alt="avatar" src="
                    {% if profile.avatar %}
                        {{ profile.avatar.avatar.url }}
                    {% else %}
                        {% static 'ressources/logo/icon_bronycub.png' %}
                    {% endif %}">
            </span>
            <h3 class="username-member">{{ profile.user.username }}</h3>
        </div>
    </a>
</div>
<div id="modal-{{profile.user.username}}" class="modal fade" role="dialog" aria-hidden="true">
    <div class="modal-dialog modal-lg">
        {% if user.is_authenticated and user.profile.enabled %}
            <div class="container-fluid modal-content modal-lg">
                <div class="modal-header">
                  <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
                  <img class="img-rounded img-avatar" alt="avatar" src="
                                {% if profile.avatar %}
                                    {{ profile.avatar.avatar.url }}
                                {% else %}
                                    {% static 'ressources/logo/icon_bronycub.png' %}
                                {% endif %}
                            ">
                  <strong style="font-size:28px;">{{ profile.user.username }}</strong>
                </div>
                <div class="modal-body">
                  <p style="word-wrap: break-word;">
                    {{ profile.bio }}
                  </p>
                  <hr />
                  <p>
                    {% for pony in profile.userpony_set.all %}
                      <img alt="{% static pony.pony.name %}" src="{% static 'img/ponies/'|add:pony.pony.file_name %}" class="img-thumbnail"/>&nbsp;<span class='label label-info'>{{ pony.message }}</span>
                    {% endfor %}
                  </p>
                  {% if profile.userpony_set.all|length > 0 %}
                    <hr />
                  {% endif %}
                  <div class="list-group col-sm-7">
                    {% if not profile.name_enabled %}
                      <a href="#" class="list-group-item"><i class="fa fa-user">&nbsp;</i>{{ profile.user.last_name }} {{ profile.user.first_name }}</a>
                    {% endif %}
                    {% if not profile.birthday_enabled %}
                      <a href="#" class="list-group-item"><i class="fa fa-birthday-cake">&nbsp;</i>{{ profile.birthday }}</a>
                    {% endif %}
                    {% if not profile.phone_enabled %}
                      <a href="#" class="list-group-item"><i class="fa fa-phone">&nbsp;</i>{{ profile.phone }}</a>
                    {% endif %}
                    {% if not profile.mail_enabled %}
                      <a href="#" class="list-group-item"><i class="fa fa-envelope">&nbsp;</i>{{ profile.user.email }}</a>
                    {% endif %}
                    {% if not profile.address_enabled %}
                      <a href="#" class="list-group-item"><i class="fa fa-map-marker">&nbsp;</i>{{ profile.address }}, {{ profile.postal_code }} {{ profile.city }}</a>
                      <a href="#" class="list-group-item"><i class="fa fa-map-marker">&nbsp;</i><button href="#" class="btn btn-info btn-xs">Localisation sur la carte</button></a>
                    {% endif %}
                  </div>
                  <div class="panel-body">
                    <div>
                          {% for url in profile.userurl_set.all %}
                              <a href='{{ url.url }}' class='zocial icon {{ url.icon.name }}'></a>
                          {% endfor %}
                    </div>
                  </div>
                </div>
            </div>
        {% elif not user.profile.enabled %}
            <div class="container-fluid">
                <div class="alert alert-danger">
                    <div class="row modal-body">
                        <p>{% trans 'Your account must be accepted by the admin to see the members informations.' %}</p>
                    </div>
                    <div class="row modal-footer">
                        <button type="button" class="btn btn-default" data-dismiss="modal">{% trans 'Close' %}</button>
                    </div>
                </div>
            </div>
        {% else %}
            <div class="container-fluid">
                <div class="alert alert-danger">
                    <div class="row modal-body">
                        <p>{% trans 'You must be connected to see the members informations.' %}</p>
                    </div>
                    <div class="row modal-footer">
                        <button type="button" class="btn btn-default" data-dismiss="modal">{% trans 'Close' %}</button>
                    </div>
                </div>
            </div>
        {% endif %}
    </div>
</div>