agenda/urls.py
from django.conf.urls         import url
from .                        import views, models
from el_pagination.views      import AjaxListView
from django.utils.translation import ugettext_lazy as _


urlpatterns = [
    url(
        regex = r'^$',
        view  = AjaxListView.as_view(model = models.Event),
        name  = 'list',
    ),
    url(
        regex = _(r'^(?P<event_id>[0-9]+)/comments$'),
        view  = views.CommentAjaxListView.as_view(),
        name  = 'comment_list',
    ),
    url(
        regex = _(r'^event$'),
        view  = views.CreateEventView.as_view(),
        name  = 'event',
    ),
    url(
        regex = _(r'^event/(?P<pk>[\d]+)$'),
        view  = views.UpdateEventView.as_view(),
        name  = 'event',
    ),
    url(
        regex = _(r'^comment$'),
        view  = views.post_comment,
        name  = 'comment',
    ),
    url(
        regex = _(r'^participations$'),
        view  = views.participate,
        name  = 'participate',
    ),
    url(
        regex = _(r'^ics$'),
        view  = views.ics_export,
        name  = 'ics_export',
    ),
    url(
        regex = _(r'^event/update/(?P<event_id>[0-9]+)$'),
        view  = views.update_event,
        name  = 'update_event',
    ),
]

core/urls.py
from django.conf.urls         import url
from django.views.generic     import TemplateView
from django.utils.translation import ugettext_lazy as _
from .                        import views

urlpatterns = [
    url(r'^$',           views.home,                                      name = 'home'),
    url(_(r'^hq$'),      TemplateView.as_view(template_name = 'hq.html'), name = 'hq'),
    url(_(r'^map$'),     views.map,                                       name = 'map'),
    url(_(r'^friends$'), views.friends,                                   name = 'friends'),
]

sugarcub/urls.py
from django.conf.urls         import include, url, i18n
from django.contrib           import admin
from django.conf              import settings
from django.conf.urls.static  import static
from django.utils.translation import ugettext_lazy as _
from django.contrib.auth      import views as auth_views
from users.forms              import AuthenticationForm


urls = [
    url(r'^captcha/', include('captcha.urls')),
    url(_(r'admin/doc/'), include('django.contrib.admindocs.urls')),
    url(_(r'admin/'),     include(admin.site.urls)),

    url(_(r'bbbff/'),     include('bbbff.urls',  namespace='bbbff')),
    url(_(r'agenda/'),    include('agenda.urls', namespace='agenda')),
    url(r'',              include('users.urls',  namespace='users')),
    url(r'',              include('core.urls',   namespace='core')),

    url(r'^login/$',
        auth_views.login,
        {
            'template_name': 'registration/login.html',
            'authentication_form': AuthenticationForm
        },
        name='auth_login'),
    url(r'',              include('registration.backends.default.urls')),
]


urlpatterns = i18n.i18n_patterns(*urls)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


handler400 = 'core.views.bad_request'
handler403 = 'core.views.permission_denied'
handler404 = 'core.views.page_not_found'
handler500 = 'core.views.server_error'

users/urls.py
from django.conf.urls         import url
from django.views.generic     import TemplateView
from django.utils.translation import ugettext_lazy as _
from .                        import views


urlpatterns = [
    url(_(r'^members$'),  views.members,                    name = 'members'),
    url(_(r'^profile$'),  views.profile,                    name = 'profile'),
    url(_(r'^register$'), views.RegistrationView.as_view(), name = 'registration_register'),
    url(_(r'^register/informations$'),
        TemplateView.as_view(template_name = 'registration/informations.html'),  name = 'pre_register'),
]

agenda/models.py
from   django.db                  import models
from   django.contrib.auth.models import User
from   django.core.urlresolvers   import reverse
from   django.utils.translation   import ugettext_lazy as _
import ics


information_enabled = (
    ('1', _('Show both my phone and my mail')),
    ('2', _('Show only my mail')),
    ('3', _('Show only my phone')),
)


class Event(models.Model):
    ''' Represent an event in the agenda '''

    author        = models.ForeignKey(User, verbose_name = _('user'))

    title         = models.CharField(_('title'), max_length = 500)
    description   = models.TextField(_('description'))
    date_begin    = models.DateTimeField(_('date begin'))
    date_end      = models.DateTimeField(_('date end'))
    address       = models.CharField(_('address'), max_length = 200)
    event_enabled = models.CharField(_('event enabled'), max_length = 10, choices = information_enabled)

    class Meta:
        ordering            = ['-date_begin', '-date_end']
        verbose_name        = _('event')
        verbose_name_plural = _('events')

    def get_absolute_url(self):
        return reverse('event', kwargs={'pk': self.pk})

    def __str__(self):
        return self.title

    def __init__(self, *args, ics_import = None, **kwargs):
        super().__init__(*args, **kwargs)
        if ics_import is not None:
            self.from_ics_event(ics_import)

    def from_ics_event(self, ics_event):
        self.title       = ics_event.name
        self.date_begin  = ics_event.begin.naive
        self.date_end    = ics_event.end.naive
        self.description = ics_event.description

    def to_ics_event(self):
        return ics.Event(
            name        = self.title,
            begin       = self.date_begin,
            end         = self.date_end,
            description = self.description,
        )


class Comment(models.Model):
    '''
    Represent a post in a discussion attached to an event

    Comment is posted by author if logged in, else by pseudo
    '''

    author = models.ForeignKey(User, verbose_name = _('user'), blank = True, null = True)
    pseudo = models.CharField(_('unregistered user'), max_length = 30, blank = True, null = True)
    event  = models.ForeignKey(Event, verbose_name = _('event'))

    text   = models.TextField(_('text'))
    date   = models.DateTimeField(_('date'), auto_now_add = True)

    class Meta:
        ordering            = ['-date']
        verbose_name        = _('comment')
        verbose_name_plural = _('comments')

    def __str__(self):
        return self.text


class Participation(models.Model):
    '''
    Represent a participation to an event by a user

    Participation is made by author if logged in, else by pseudo
    '''

    user    = models.ForeignKey(User, verbose_name = _('user'), null = True, blank = True)
    pseudo  = models.CharField(_('unregistered user'), max_length = 31, blank = True, null=True)
    contact = models.CharField(_('contact'), max_length = 31, blank = True, null = True)
    event   = models.ForeignKey(Event, verbose_name = _('event'))

    class Meta:
        ordering            = ['pseudo']
        verbose_name        = _('participation')
        verbose_name_plural = _('participations')
        unique_together     = (
            ('user', 'event'),
            ('pseudo', 'event'),
        )

    def __str__(self):
        return str(self.author()) + ' ' + str(self.event)

    def author(self):
        return self.user if self.user else self.pseudo

core/models.py
from django.db                import models
from django.utils.translation import ugettext_lazy as _


class Quote(models.Model):
    ''' List of quotes in the home page '''

    quote = models.TextField(_('quote'))

    class Meta:
        verbose_name        = _('quote')
        verbose_name_plural = _('quotes')

    def __str__(self):
        return self.quote


class Friend(models.Model):
    ''' List of other collectives shown as your friends '''

    name        = models.CharField(_('name'), max_length = 32)
    description = models.TextField(_('description'))
    image       = models.ImageField(_('image'))
    url         = models.URLField(_('url'))

    class Meta:
        verbose_name        = _('friend')
        verbose_name_plural = _('friends')

    def __str__(self):
        return self.name

agenda/forms.py
from django                      import forms
from .                           import models
from bootstrap3_datetime.widgets import DateTimePicker
from django.utils.translation    import ugettext_lazy as _
from captcha.fields              import CaptchaField


class EventForm(forms.ModelForm):

    date_begin = forms.DateTimeField(
        widget = DateTimePicker(
            options = {
                'format': 'DD/MM/YYYY HH:mm',
            }
        ),
        label = _('Start date and hour')
    )
    date_end = forms.DateTimeField(
        widget = DateTimePicker(
            options = {
                'format': 'DD/MM/YYYY HH:mm',
            }
        ),
        label = _('End date and hour')
    )

    class Meta:
        model  = models.Event
        exclude = ['author']
        labels = {
            'title':         _('Title'),
            'description':   _('Description'),
            'address':       _('Address of the event'),
            'event_enabled': _('Means of contact')
        }

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['description'].widget.attrs.update({'placeholder':
            _('Explain the event, add as much information you can : time, localisation '
                ', if people need stuff... the more information the better!')
        })


class CommentForm(forms.ModelForm):

    captcha = CaptchaField()

    class Meta:
        model  = models.Comment
        fields = ['text', 'pseudo']
        labels = {
            'text': _('Add a comment about the event...')
        }


class ParticipationForm(forms.ModelForm):

    captcha = CaptchaField()

    class Meta:
        model = models.Participation
        fields = ['pseudo', 'contact']

agenda/views.py
from django.shortcuts               import render
from django.core.urlresolvers       import reverse_lazy
from django.views.generic.edit      import CreateView, UpdateView
from .                              import models, forms, utils
from .forms                         import EventForm, CommentForm, ParticipationForm
from el_pagination.views            import AjaxListView
from django.http                    import HttpResponse
from django.shortcuts               import redirect
from django.contrib.auth.decorators import login_required
from django.utils.decorators        import method_decorator
import json


class CommentAjaxListView(AjaxListView):

    form_class = forms.CommentForm

    def get_queryset(self):
        return models.Comment.objects.filter(event = self.kwargs['event_id'])


class CreateEventView(CreateView):

    form_class    = forms.EventForm
    success_url   = reverse_lazy('agenda:list')
    template_name = 'agenda/event_form.html'

    @method_decorator(login_required)
    def dispatch(self, *args, **kwargs):
        return super().dispatch(*args, **kwargs)

    def form_valid(self, form):
        instance = form.save(commit = False)
        instance.author = self.request.user
        instance.save()
        utils.send_new_event_notification.delay(instance.id)
        return super().form_valid(form)


class UpdateEventView(UpdateView):

    model         = models.Event
    form_class    = forms.EventForm
    success_url   = reverse_lazy('agenda:list')
    template_name = 'agenda/event_form.html'

    @method_decorator(login_required)
    def dispatch(self, *args, **kwargs):
        return super().dispatch(*args, **kwargs)


def post_comment(request):

    if request.POST:
        captcha = CommentForm(request.POST)
        if request.user.is_authenticated():
            event = models.Event.objects.get(pk = request.POST.get('event'))
            comment = models.Comment(
                author = request.user,
                text = request.POST.get('text'),
                event = event
            )
            comment.save()

        else:
            if captcha.is_valid():
                event = models.Event.objects.get(pk = request.POST.get('event'))
                comment = models.Comment(
                    pseudo = request.POST.get('pseudo'),
                    text = request.POST.get('text'),
                    event = event
                )
                comment.save()
            else:
                return HttpResponse(json.dumps(captcha.errors), status=400)

        return HttpResponse('success')


def participate(request):

    if request.method == 'POST':
        captcha = ParticipationForm(request.POST)
        if request.user.is_authenticated():
            event = models.Event.objects.get(pk = request.POST.get('event'))
            participation = models.Participation(
                user = request.user,
                event = event
            )
            try:
                participation.save()
            except:
                return HttpResponse(json.dumps(captcha.errors), status=400)

        else:
            if captcha.is_valid():
                event = models.Event.objects.get(pk = request.POST.get('event'))
                participation = models.Participation(
                    pseudo = request.POST.get('pseudo'),
                    event = event,
                    contact = request.POST.get('contact'),
                )
                try:
                    participation.save()
                except:
                    return HttpResponse(json.dumps(captcha.errors), status=400)

        return HttpResponse('success')

    return redirect('agenda:list')


def ics_export(request):
    calendar = str(utils.export_calendar())
    response = HttpResponse(calendar, content_type = 'text/calendar; charset=utf-8')
    response['Content-Disposition'] = 'attachment; filename=agenda.ics'
    response['Content-Lenght'] = len(calendar)
    return response


def update_event(request, event_id):
    try:
        event = models.Event.objects.get(id = event_id)
    except:
        return redirect('agenda:list')

    if event.author.id == request.user.id:
        if request.method == 'POST':

            form = EventForm(request.POST, request.FILES, instance = event)

            if form.is_valid():
                form.save()

                return redirect('agenda:list')

        else:
            form = EventForm(instance = event)

        return render(request, 'agenda/event_update_form.html', {
            'event':   event,
            'form':    form,
        })

    else:
        return redirect('agenda:list')

core/views.py
from   django.shortcuts  import render
from   django.conf       import settings
from   .models           import Friend, Quote
from   users.models      import Profile
from   django.core.cache import cache
import requests
import re
import random


def home(request):

    irc = cache.get('irc_log')
    if not irc:
        try:
            irc = requests.get('http://www.art-software.fr/files/lastlog_bronycub.php').text
            irc = re.sub(r'(.*(kick|ban).*)',          r'<span class="text-warning">\1</span>', irc)
            irc = re.sub(r'(&lt;[a-zA-Z0-9\-_]*&gt;)', r'<span class="text-primary">\1</span>', irc)
            irc = re.sub(r'(.*\*\*\*.*)',              r'<span class="text-info">\1</span>',    irc)
            cache.set('irc_log', irc)
        except:
            irc = ''

    quotes = list(Quote.objects.all())
    random.shuffle(quotes)

    return render(request, 'home.html', {
        'irc':      irc,
        'quotes':   quotes,
        'birthday': Profile.objects.get_birthday(),
        'new':      Profile.objects.get_new_members(),
        'list_new': len(Profile.objects.get_new_members()),
    })


def agenda(request):

    return render(request, 'agenda.html')


def map(request):

    return render(request, 'map.html', {
        'fillPage':        True,
        'profiles':        Profile.objects.get_active_users(),
        'OSM_TILE_SERVER': settings.OSM_TILE_SERVER,
    })


def friends(request):

    friends = Friend.objects.all()

    if friends.count() > 2:
        friend_width = 4
    elif friends.count() == 2:
        friend_width = 6
    else:
        friend_width = 12

    return render(request, 'friends.html', {
        'friends':     friends,
        'friendWidth': friend_width,
    })


def bad_request(request):
    return render(request, 'errors/bad_request.html', status=400)


def permission_denied(request):
    return render(request, 'errors/permission_denied.html', status=403)


def page_not_found(request):
    return render(request, 'errors/page_not_found.html', status=404)


def server_error(request):
    return render(request, 'errors/server_error.html', status=500)

core/templates/agenda.html
{% extends "base.html" %}

{% load static %}
{% load i18n %}

{% block title %}{% trans 'Agenda' %}{% endblock %}

{% block body %}
    {{ block.super }}
    <div class="container">
        <div class="row">
            <div class="col-xs-12">
                <h1>TODO | Agenda</h1>
            </div>
        </div>
    </div>
{% endblock %}

core/templates/banner.html
{% load i18n %}

{% if user.is_authenticated %}
    {% if not user.profile.avatar %}
        <div class="alert alert-dismissible alert-warning">{% trans 'Your profile is uncomplete, remember to complete it!' %}</div>
    {% endif %}
    {% if not user.profile.enabled %}
        <div class="alert alert-dismissible alert-danger">{% trans 'Your profile is still unapproved by an admin. Until it is, some part of the site will not be avaible for you' %}</div>
    {% endif %}
{% endif %}

core/templates/base.html
{% load static %}
{% load i18n %}
{% load pipeline %}

<!doctype html>
<html lang="{{ LANGUAGE_CODE|default:"en-us" }}" {% if LANGUAGE_BIDI %}dir="rtl"{% endif %}>
    <head>
        {% block head %}
            <meta charset="UTF-8">
            <meta name="viewport" content="width=device-width, initial-scale=1.0">
            <title>{{ collective_name }} | {% block title %}{% endblock %}</title>
            <link rel="shortcut icon" type="image/png" href="{% static 'ressources/logo/favicon_bronycub.png' %}" />
            {% stylesheet 'css' %}
            {% block stylesheets %}
                {% block extrastyle %}{% endblock %}
            {% endblock %}

            {% javascript 'js' %}
            {% block javascripts %}
                <script>
                    window.cookieconsent_options = {
                        theme: false,
                        message: 'Ce site utilise des cookies pour vous assurez une meilleure expérience possible.',
                        dismiss: 'OK :)',
                        markup: [
                            '<div class="cc_banner-wrapper">',
                                '<div class="cc_banner cc_container cc_container--open">',
                                    '<a href="#null" data-cc-event="click:dismiss" target="_blank" class="cc_btn cc_btn_accept_all">OK /)</a>',
                                    '<p class="cc_message">Ce site utilise des cookies pour vous assurez une meilleure expérience possible.</p>',
                                '</div>',
                            '</div>'
                        ]
                    };
                </script>
                {% block extrascripts %}{% endblock %}
            {% endblock %}

            {% block blockbots %}{% endblock %}
            {% block extrahead %}{% endblock %}
        {% endblock %}
    </head>
    <body>

        {% block header %}
            <header>
                <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
                    <div class="container-fluid">
                        <div class="navbar-header">
                            <a href="{% url 'core:home' %}" class="navbar-brand">{{ collective_name }}</a>
                            <button class="navbar-toggle" type="button" data-toggle="collapse" data-target="#navbar-main">
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                            </button>
                        </div>
                        <div class="navbar-collapse collapse" id="navbar-main">
                            <ul class="nav navbar-nav">
                                <li><a href="{% url 'users:members' %}"><i class="fa fa-user fa-1x"></i>&nbsp;{% trans 'Members' %}</a></li>
                                <li><a href="{% url 'agenda:list' %}"><i class="fa fa-calendar fa-1x"></i>&nbsp;{% trans 'Agenda' %}</a></li>
                                <li><a href="{% url 'core:hq' %}"><i class="fa fa-glass fa-1x"></i>&nbsp;{% trans 'HQ' %}</a></li>
                                <li><a href="https://goo.gl/photos/VisPhiPgauSD8QXn7{# url '' #}"><i class="fa fa-picture-o fa-1x"></i>&nbsp;{% trans 'Medias' %}</a></li>
                                <li><a href="{% url 'core:map' %}"><i class="fa fa-map-marker fa-1x"></i>&nbsp;{% trans 'Map' %}</a></li>
                                <li><a href="{% url 'core:friends' %}"><i class="fa fa-heart fa-1x"></i>&nbsp;{% trans 'Friends' %}</a></li>
                            </ul>
                            <ul class="nav navbar-nav navbar-right">
                                <li><a href="https://kiwiirc.com/client?settings=3ebf3eb7a40c2b03f47b918eb2f7087a" target="_blank"><i class="fa fa-comment fa-1x"></i>&nbsp;{% trans 'Tchat' %}</a></li>
                                <li><a href="https://vroom.im/bronycub" target="_blank"><i class="fa fa-video-camera fa-1x"></i>&nbsp;{% trans 'Visio' %}</a></li>
                                {% if user.is_authenticated %}
                                    <li class="hidden-lg">
                                        <a class="text-right username-header-small">
                                            <img class="img-header-small" alt="avatar" src="
                                                {% if user.profile.avatar.small %}
                                                    {{ user.profile.avatar.small.url }}
                                                {% else %}
                                                    {% static 'ressources/logo/icon_bronycub.png' %}
                                                {% endif %}
                                            "/>
                                            {{ user.username }}
                                        </a>
									</li>
									<li class="hidden-lg"><a href="{% url 'users:profile' %}" class=""><i class="fa fa-user fa-1x"></i>&nbsp;{% trans 'Profile' %}</a></li>
									{% if user.is_staff %}
										<li class="hidden-lg"><a href="{% url 'admin:index' %}" class=""><i class="glyphicon glyphicon-cog"></i>&nbsp;{% trans 'Admin' %}</a></li>
									{% endif %}
									<li class="hidden-lg"><a href="{% url 'auth_logout' %}"><i class="fa fa-sign-out fa-1x"></i>&nbsp;{% trans 'Logout' %}</a></li>
                                    <li role="presentation" class="dropdown visible-lg-block">
                                        <a class="dropdown-toggle" data-toggle="dropdown" href="#" role="button" aria-expanded="false">
                                            <img class="img-header" alt="avatar" src="
                                                {% if user.profile.avatar.small %}
                                                    {{ user.profile.avatar.small.url }}
                                                {% else %}
                                                    {% static 'ressources/logo/icon_bronycub.png' %}
                                                {% endif %}
                                            "/>
                                            {{ user.username }}
                                            <span class="caret"></span>
                                        </a>
                                        <ul class="dropdown-menu" role="menu">
                                            <li><a href="{% url 'users:profile' %}" class=""><i class="fa fa-user fa-1x"></i>&nbsp;{% trans 'Profile' %}</a></li>
                                            {% if user.is_staff %}
                                                <li><a href="{% url 'admin:index' %}" class=""><i class="glyphicon glyphicon-cog"></i>&nbsp;{% trans 'Admin' %}</a></li>
                                            {% endif %}
                                            <li><a href="{% url 'auth_logout' %}"><i class="fa fa-sign-out fa-1x"></i>&nbsp;{% trans 'Logout' %}</a></li>
                                        </ul>
                                    </li>
                                {% else %}
                                    <li><a href="{% url 'auth_login' %}"><!-- data-toggle="modal" data-target="#LoginForm"--><i class="fa fa-sign-in fa-1x"></i>&nbsp;{% trans 'Login' %}</a></li>
                                    <li><a href="{% url 'users:pre_register' %}"><i class="fa fa-plus fa-1x"></i>&nbsp;{% trans 'Signup' %}</a></li>
                                {% endif %}
                            </ul>
                        </div>
                    </div>
                </nav>
            </header>
        {% endblock %}

        <div id="content"
            {% if fillPage %}
                class="min-size full-height"
            {% endif %}
        >
            <div class="container">
                <div class="row">
                    <div class="col-xs-12">
                        {% include 'banner.html' %}
                    </div>
                </div>
            </div>
            {% block body %}
                <div id="WhenIm"></div>
            {% endblock %}

            {% block footer %}
                <footer class="container-fluid">
                    <div class="row">
                        <div class="col-xs-12 col-md-7 col-md-offset-1">
                            <div class="well">
                                <a href="http://asbf.info" target="_blank"><img src="http://asbf.info/img/header.png" alt="logo_asbf" height="60px" class="asbf"/></a>
                                <p>Depuis 2015, BronyCUB est Acteur Solidaire de l'association <a href="http://asbf.info" target="_blank">ASBF</a> réunissant tous les Bronies Francophone solidairement pour des actions humanitaires. Ainsi, notre collectif agit sur Bordeaux au nom de cette association.</p>
                            </div>
                        </div>
                        <div class="col-xs-12 col-md-3 text-center">
                            <h4>
                                <i class="fa fa-envelope"></i>&nbsp;&nbsp;{% trans 'Contact us :' %}
                                <img src="{% static 'img/derpy.gif' %}" width="50" alt="DerpyHooves"/>
                            </h4>
                                <a class="btn btn-primary btn-lg" href="mailto:{{ mailing_list }}">{{ mailing_list }}</a>
                              <p class="powered-by">
                                <a href="http://sugarcub.org">{% trans 'Powered by' %} <img src="http://sugarcub.org/img/logo_sugarcub.png" alt="Logo SugarCUB" height="30px"></a>
                              </p>
                        </div>
                    </div>
                </footer>
            {% endblock %}
        </div>
    </body>
</html>

core/templates/friends.html
{% extends "base.html" %}

{% load static %}
{% load i18n %}

{% block title %}{% trans 'Friends' %}{% endblock %}

{% block body %}
    {{ block.super }}

    <div class="container">
        <div class="row">

            {% for friend in friends %}
                {% if forloop.counter0|divisibleby:3 and not forloop.first %}
                    </div>
                    <div class="row">
                {% endif %}
                <div class="col-md-{{ friendWidth }} text-center">
                    <div class="panel panel-info">
                        <div class="panel-heading">{{ friend.name }}</div>
                      <div class="panel-body panel-min-height">
                          <a href="{{ friend.url }}" target="_blank">
                              <img class="thumbnail img-responsive center-block" src="{{ friend.image.url }}" alt="Image{{ friend.name }}">
                        </a>
                        <p>{{ friend.description }}</p>
                      </div>
                    </div>
                </div>
            {% empty %}
                <p>{% trans 'No friends at the moment...' %}</p>
            {% endfor %}

        </div>
    </div>
{% endblock %}

core/templates/hq.html
{% extends "base.html" %}

{% load static %}
{% load i18n %}

{% block title %}{% trans 'HQ' %}{% endblock %}

{% block body %}
{{ block.super }}

<div class="container">
    <div class="col-xs-12">
        <h2><strong>À venir : </strong>Le Quartier Général de BronyCUB !</h2>
    </div>
</div>
{% endblock %}

core/templates/map.html
{% extends 'base.html' %}

{% load static %}
{% load i18n %}

{% block stylesheets %}
    {{ block.super }}
    <link rel="stylesheet" href="{% static 'leaflet/leaflet.css' %}" />
{% endblock %}

{% block title %}{% trans 'Map' %}{% endblock %}

{% block body %}
    {{ block.super }}
    <div class="container-fluid map-size">
        <div class="row full-height">
            <div class="col-xs-12 full-height">
                <div id="map" class="full-height"></div>
            </div>
        </div>
    </div>
    <div class="col-xs-12 text-center">
        <a class="btn btn-success btn-lg" href="{% url 'core:hq' %}">{% trans 'Access HQ' %}</a>
        <a class="btn btn-primary btn-lg" href="http://carte.leponeyblanc.fr/">{% trans 'Map of France' %}</a>
    </div>
{% endblock %}

{% block javascripts %}
    {{ block.super }}
    <script src="{% static 'leaflet/leaflet.js' %}"></script>
    <script>
        $(document).ready(function() {
            var map = L.map('map').setView([44.836517, -0.583233], 13);

            L.tileLayer('https://{s}.{{ OSM_TILE_SERVER }}/{z}/{x}/{y}.png', {
                maxZoom: 18,
                attribution: 'Map data &copy; <a href="http://openstreetmap.org">OpenStreetMap</a> contributors, ' +
                    '<a href="http://creativecommons.org/licenses/by-sa/2.0/">CC-BY-SA</a>, ' +
                    'Imagery © <a href="http://openstreetmap.org">OpenStreetMap</a>',
            }).addTo(map);

            {% if user.is_authenticated and user.profile.enabled %}
                {% for profile in profiles %}
                    {% if profile.address_latitude and profile.address_longitude %}
                        var customIcon = L.icon({
                            iconUrl: {% if profile.avatar %}
                                        '{{ profile.avatar.avatar.url }}',
                                     {% else %}
                                         {# set rand = random(2)+1 #}
                                         '{% static 'ressources/logo/berry_punch_1-small.png' %}',
                                     {% endif %}
                            iconSize: [40, 40],
                            iconAnchor: [20, 40],
                            popupAnchor: [0, -40]
                        });
                        L.marker(
                            [{{ profile.address_latitude|safe}}, {{profile.address_longitude|safe }}],{
                                icon: customIcon
                            }
                        ).addTo(map).bindPopup("{{ profile.user.username }}").openPopup();
                    {% endif %}
                {% endfor %}
            {% endif %}

            var popup = L.popup();
        });
    </script>
{% endblock %}